# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# I deliberately left all repos to be remote, to avoid installing any
# extraneous packages that are not relevant to the project.
# Additionally, this configuration severely restricts the files on which these
# hooks are run. This is preliminary, and hopefully, these restrictions are 
# lifted to run these checks on all the files in the repository. 

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black-jupyter
        args: ["--config=./pyproject.toml"]
        types_or: [python, jupyter] 
      - id: black
        args: ["--config=./pyproject.toml"]
        types_or: [python]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--sp=./.isort.cfg"]
        types_or: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [
          "--config=./.flake8.cfg",
          "--exit-zero",
        ]
        types_or: [python]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
        args: ["--config=./pyproject.toml"]
        types_or: [python, jupyter]
      - id: nbqa-check-ast
        types_or: [python, jupyter]
      - id: nbqa-isort
        args: ["--sp=./.isort.cfg"]
        types_or: [python, jupyter]
      - id: nbqa-flake8
        args: [
          "--config=./.flake8.cfg",
          "--exit-zero",
        ]
        types_or: [python, jupyter]
      - id: nbqa-pyupgrade
        args: ["--py36-plus"]
        types_or: [python, jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        types_or: [python, jupyter]
      - id: trailing-whitespace
        types_or: [python, jupyter]
      - id: mixed-line-ending
        types_or: [python, jupyter]
      - id: requirements-txt-fixer
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: check-ast
        types_or: [python]
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=10240"]  # 10MB max

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-tabs
        types_or: [python, jupyter]
      - id: forbid-crlf
        types_or: [python, jupyter]

 #- repo: https://github.com/kynan/nbstripout
 #  rev: 0.5.0
 #  hooks:
 #    - id: nbstripout
 #      types_or: [python, jupyter]
