# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.com/index.html#config-files for how-to-use config files
#
# See https://towardsdatascience.com/getting-started-with-python-pre-commit-hooks-28be2b2d09d5
# for a tutorial on getting started with pre-commit hooks. This tutorial uses
# poetry and other tools in the stack; but the example pre-commit-config.yaml
# is "more tweaked" compared to other examples I have come across.
#
# See https://engineeringfordatascience.com/posts/pre_commit_yaml/ for how to
# use pre-commit in data science projects. The sample pre-commit-config.yaml
# file (in a somewhat modified form) is what is used here.
#
# See https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
# for how black and flake8 are not compatible out-of-the-box. The additional
# arguments to these two tools listed below, are meant to find agreement
# between best practises in these two worlds.
#
# I deliberately left all repos to be remote, to avoid installing any
# extraneous packages that are not relevant to the project.

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black-jupyter
        args: ["--config=./.black"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-isort
        args: ["--sp=./.isort"]
      - id: nbqa-black
        args: ["--config=./.black"]
        # - id: nbqa-flake8
        # args: ["--config=./.flake8"]
      - id: nbqa-pyupgrade
        args: ["--py36-plus"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: check-case-conflict
      - id: check-added-large-files

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-tabs
      - id: forbid-crlf

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
