name: lexnorm
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - colorama=0.4.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.15.2
  - ipython=8.6.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jupyter_client=7.4.7
  - jupyter_core=4.11.2
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - llvm-openmp=14.0.6
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyparsing=3.0.9
  - python=3.9.12
  - python-crfsuite=0.9.7
  - python-dateutil=2.8.2
  - pytz=2022.1
  - pyzmq=23.2.0
  - readline=8.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.5.0
  - six=1.16.0
  - sklearn-crfsuite=0.3.6
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tabulate=0.9.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - tzdata=2022f
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.13
